// ==============================================================================
// VM native-execution arena (RWX memory for running generated machine code).
// ==============================================================================
//
// BOUNDARY (由щ럭 吏??#20): ??Arena ??**build/test-time 寃利??뚮뱶諛뺤뒪**?대ŉ
// ?쒗뭹 PE ?뚯씠?꾨씪??src/pipeline/*)?먮뒗 ?덈? 李몄“?섏? ?딅뒗?? 寃利앸맂 VM 肄붾뱶??// PE 濡?鍮뚮뱶?섏뼱 諛고룷?섍퀬, 諛고룷 ?고??꾩쓽 肄붾뱶 ?섏씠吏??mem_harden ??RW ??RX 濡?// ?꾪솚??W^X) ?ㅽ뻾?쒕떎. ?ш린??Arena 媛 RWX 瑜??곕뒗 ?댁쑀?? VM ??媛숈? 留ㅽ븨??// state(0x6000)/data(0x9000) ?곸뿭??*?ㅽ뻾 以? 吏곸젒 ?쎄퀬 ?곌린 ?뚮Ц??肄붾뱶?
// ?곗씠?곕? ???섏씠吏 洹몃９?쇰줈 遺꾨━(seal)?????녾린 ?뚮Ц?대떎.
//
// P1-2 (W^X): `seal()`/`unseal()`濡?RW ??RX ?꾪솚???쒓났?쒕떎. ?먯껜 ?꾧껐
// (arena ?곗씠?곕? ?쎌? ?딅뒗) 肄붾뱶??seal(RX) ???ㅽ뻾??W^X 怨꾩빟??吏?????덈떎.
// 肄붾뱶? ?곗씠?곕? ?꾩쟾??遺꾨━ 留ㅽ븨?쇰줈 ?섎늻???묒뾽???꾩슂?섎㈃ ???뚯씪?먯꽌 ?쒖옉?쒕떎.

use anyhow::{anyhow, Result};

/// Native-execution arena: RWX memory to run generated machine code.
///
/// Platform backends:
///   * Unix   ??`mmap`/`munmap` (via `libc`)
///   * Windows??`VirtualAlloc`/`VirtualFree` (raw kernel32 FFI, no extra crate)
pub(crate) struct Arena {
    pub(crate) base: usize,
    pub(crate) size: usize,
}

#[cfg(unix)]
impl Arena {
    pub(crate) fn new(size: usize) -> Result<Arena> {
        // SAFETY: standard mmap call for an anonymous RWX mapping.
        let p = unsafe {
            libc::mmap(
                std::ptr::null_mut(),
                size,
                libc::PROT_READ | libc::PROT_WRITE | libc::PROT_EXEC,
                libc::MAP_PRIVATE | libc::MAP_ANONYMOUS,
                -1,
                0,
            )
        };
        if p == libc::MAP_FAILED {
            return Err(anyhow!("VM self-test: mmap RWX failed"));
        }
        Ok(Arena {
            base: p as usize,
            size,
        })
    }

    pub(crate) fn bytes(&mut self) -> &mut [u8] {
        // SAFETY: arena owns the mapping for `size` bytes.
        unsafe { std::slice::from_raw_parts_mut(self.base as *mut u8, self.size) }
    }

    /// P1-2 (W^X): RW ??RX (seal). ?먯껜 ?꾧껐 肄붾뱶 ?ㅽ뻾 ?꾩뿉 ?몄텧.
    pub fn seal(&self) -> Result<()> {
        // SAFETY: mprotect on our own mapping.
        let r = unsafe {
            libc::mprotect(
                self.base as *mut libc::c_void,
                self.size,
                libc::PROT_READ | libc::PROT_EXEC,
            )
        };
        if r != 0 {
            return Err(anyhow!("VM self-test: mprotect -> RX failed"));
        }
        // SAFETY: instruction-cache flush for non-coherent targets (no-op on x86_64).
        unsafe {
            libc::__clear_cache(
                self.base as *mut libc::c_void,
                (self.base + self.size) as *mut libc::c_void,
            );
        }
        Ok(())
    }

    /// P1-2 (W^X): RX ??RW (unseal).
    pub fn unseal(&self) -> Result<()> {
        // SAFETY: mprotect on our own mapping.
        let r = unsafe {
            libc::mprotect(
                self.base as *mut libc::c_void,
                self.size,
                libc::PROT_READ | libc::PROT_WRITE,
            )
        };
        if r != 0 {
            return Err(anyhow!("VM self-test: mprotect -> RW failed"));
        }
        Ok(())
    }

    /// Execute raw machine code placed at `off` within the arena.
    pub(crate) fn call(&self, off: usize) {
        // SAFETY: the code was generated by us and validated; arena is RWX.
        let f: extern "C" fn() = unsafe { std::mem::transmute(self.base + off) };
        f();
    }

    /// Execute machine code that returns a u64 (RAX) ??native bridge helper.
    pub(crate) fn call_u64(&self, off: usize) -> u64 {
        // SAFETY: transmuted to a return-value signature; arena is RWX.
        let f: extern "C" fn() -> u64 = unsafe { std::mem::transmute(self.base + off) };
        f()
    }

    /// Execute machine code with 5 Win64 args (BTG-C1 native equivalence tests).
    pub(crate) fn call5(&self, off: usize, a1: usize, a2: u64, a3: u32, a4: usize, a5: usize) {
        // SAFETY: generated code with the exact (ptr, u64, u32, ptr, ptr) ABI.
        let f: extern "C" fn(usize, u64, u32, usize, usize) =
            unsafe { std::mem::transmute(self.base + off) };
        f(a1, a2, a3, a4, a5);
    }

    /// Execute machine code with 2 Win64 args (BTG-C1 crypt blob: buf, len).
    pub(crate) fn call2(&self, off: usize, a1: usize, a2: u64) {
        // SAFETY: generated code with the exact (ptr, u64) ABI.
        let f: extern "C" fn(usize, u64) = unsafe { std::mem::transmute(self.base + off) };
        f(a1, a2);
    }
}

#[cfg(unix)]
impl Drop for Arena {
    fn drop(&mut self) {
        // SAFETY: munmap of a mapping we created.
        unsafe {
            libc::munmap(self.base as *mut libc::c_void, self.size);
        }
    }
}

#[cfg(windows)]
mod arena_win {
    use super::*;

    // Raw kernel32 FFI (stable ABI, available on all Windows targets).
    unsafe extern "system" {
        fn VirtualAlloc(
            lp_address: *mut std::ffi::c_void,
            dw_size: usize,
            fl_allocation_type: u32,
            fl_protect: u32,
        ) -> *mut std::ffi::c_void;
        fn VirtualFree(lp_address: *mut std::ffi::c_void, dw_size: usize, dw_free_type: u32)
            -> i32;
        fn VirtualProtect(
            lp_address: *mut std::ffi::c_void,
            dw_size: usize,
            fl_new_protect: u32,
            lpfl_old_protect: *mut u32,
        ) -> i32;
    }
    const MEM_COMMIT: u32 = 0x1000;
    const MEM_RESERVE: u32 = 0x2000;
    const MEM_RELEASE: u32 = 0x8000;
    const PAGE_EXECUTE_READWRITE: u32 = 0x40;
    const PAGE_EXECUTE_READ: u32 = 0x20;
    const PAGE_READWRITE: u32 = 0x04;

    impl Arena {
        /// P1-2 (W^X): 肄붾뱶瑜?RX濡?怨좎젙(seal)?쒕떎. 洹???`bytes()`濡??곕㈃ AV ??        /// ?곗씠?곕뒗 `unseal` ?꾩뿉留??대떎. (?먯껜 ?꾧껐 肄붾뱶 ?ㅽ뻾 ?쒖뿉留?seal ?ъ슜.)
        pub fn seal(&self) -> Result<()> {
            let mut old = 0u32;
            // SAFETY: VirtualProtect on our own allocation.
            let r = unsafe {
                VirtualProtect(
                    self.base as *mut std::ffi::c_void,
                    self.size,
                    PAGE_EXECUTE_READ,
                    &mut old,
                )
            };
            if r == 0 {
                return Err(anyhow!("VM self-test: VirtualProtect -> RX failed"));
            }
            Ok(())
        }

        /// P1-2 (W^X): RX ??RW 濡??섎룎???곗씠??肄붾뱶瑜??ㅼ떆 ?????덇쾶 ?쒕떎.
        pub fn unseal(&self) -> Result<()> {
            let mut old = 0u32;
            // SAFETY: VirtualProtect on our own allocation.
            let r = unsafe {
                VirtualProtect(
                    self.base as *mut std::ffi::c_void,
                    self.size,
                    PAGE_READWRITE,
                    &mut old,
                )
            };
            if r == 0 {
                return Err(anyhow!("VM self-test: VirtualProtect -> RW failed"));
            }
            Ok(())
        }

        pub fn new(size: usize) -> Result<Arena> {
            // SAFETY: VirtualAlloc RWX; fails with null on error.
            let p = unsafe {
                VirtualAlloc(
                    std::ptr::null_mut(),
                    size,
                    MEM_COMMIT | MEM_RESERVE,
                    PAGE_EXECUTE_READWRITE,
                )
            };
            if p.is_null() {
                return Err(anyhow!("VM self-test: VirtualAlloc RWX failed"));
            }
            Ok(Arena {
                base: p as usize,
                size,
            })
        }

        pub fn bytes(&mut self) -> &mut [u8] {
            // SAFETY: arena owns the allocation for `size` bytes.
            unsafe { std::slice::from_raw_parts_mut(self.base as *mut u8, self.size) }
        }

        /// Execute raw machine code placed at `off` within the arena.
        pub fn call(&self, off: usize) {
            // SAFETY: the code was generated by us and validated; arena is
            // PAGE_EXECUTE_READWRITE so it is both writable and executable.
            let f: extern "C" fn() = unsafe { std::mem::transmute(self.base + off) };
            f();
        }

        /// Execute machine code that returns a u64 (RAX) ??native bridge helper.
        pub fn call_u64(&self, off: usize) -> u64 {
            // SAFETY: transmuted to a return-value signature; arena is RWX.
            let f: extern "C" fn() -> u64 = unsafe { std::mem::transmute(self.base + off) };
            f()
        }

        /// Execute machine code with 5 Win64 args (BTG-C1 native equivalence tests).
        pub fn call5(&self, off: usize, a1: usize, a2: u64, a3: u32, a4: usize, a5: usize) {
            // SAFETY: generated code with the exact (ptr, u64, u32, ptr, ptr) ABI.
            let f: extern "C" fn(usize, u64, u32, usize, usize) =
                unsafe { std::mem::transmute(self.base + off) };
            f(a1, a2, a3, a4, a5);
        }

        /// Execute machine code with 2 Win64 args (BTG-C1 crypt blob: buf, len).
        pub fn call2(&self, off: usize, a1: usize, a2: u64) {
            // SAFETY: generated code with the exact (ptr, u64) ABI.
            let f: extern "C" fn(usize, u64) = unsafe { std::mem::transmute(self.base + off) };
            f(a1, a2);
        }
    }

    impl Drop for Arena {
        fn drop(&mut self) {
            // SAFETY: VirtualFree of an allocation we created.
            unsafe {
                VirtualFree(self.base as *mut std::ffi::c_void, 0, MEM_RELEASE);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// P1-2 (W^X): RW濡?肄붾뱶瑜??곌퀬 -> RX(seal)濡??ㅽ뻾?섍퀬 -> RW(unseal)濡??ш린濡?
    /// sealed ?곹깭?먯꽌 bytes()濡??곕㈃ AV媛 ?섏빞 ?섎?濡?unseal ?꾩뿉留??대떎.
    #[test]
    fn seal_rx_executes_and_unseal_rewrites() {
        let mut a = Arena::new(0x1000).unwrap();
        a.bytes()[0] = 0xC3; // ret
        a.call(0); // 기본(RWX) 실행
        a.seal().unwrap(); // RW -> RX (W^X)
        a.call(0); // RX 코드 실행
        a.unseal().unwrap(); // RX -> RW
        a.bytes()[0] = 0xC3; // 재기록 가능
        a.seal().unwrap();
        a.call(0);
        a.unseal().unwrap();
    }
}
