// ==============================================================================
// BTG v21 - VM Flag Model (x86 status-flag semantics, pure Rust)
// ==============================================================================
//
// M1 of the code-virtualization roadmap. The VM now models the x86 status
// flags (CF/PF/AF/ZF/SF/OF) in a single 64-bit STATE_FLAGS slot using the same
// bit positions as the real RFLAGS register (see bytecode.rs). These helpers
// compute the flag word that x86 would set for each operation, exactly matching
// the semantics of the native handlers (which use pushfq to capture real flags).
//
// This module is the *single source of truth* for the flag math. The reference
// interpreter (interp.rs) uses it, and the self-test cross-checks it against
// the native x86-64 handlers generated by handlers.rs.
//
// Semantics follow Intel SDM for the 32-bit forms we virtualize:
//   * ADD/SUB/CMP/INC/DEC : all six flags defined (INC/DEC preserve CF).
//   * AND/XOR/OR          : ZF/SF/PF defined; CF=OF=0; AF is undefined on x86,
//                           so we *define* it as 0 (the native handler masks it
//                           out too, keeping the two sides identical).
//   * MUL/IMUL            : CF/OF defined (upper-half overflow, see below); the
//                           other status flags are undefined on x86 so they pass
//                           through unchanged (P0-⑤ — matches the RISC reference
//                           `set_cf_of` exactly, so interp == native == RISC).
//   * DIV/IDIV            : flags are *undefined* on x86, so they pass through
//                           unchanged (both the native handler and the RISC
//                           reference leave them untouched).
// ==============================================================================


use crate::vm::bytecode::{F_AF, F_CF, F_OF, F_PF, F_SF, F_ZF};

/// x86 PF: set iff the low byte has an even number of set bits.
#[inline]
fn parity8(r: u32) -> bool {
    (r as u8).count_ones() % 2 == 0
}

/// Flags for ADD (r = a + b, 32-bit).
pub fn add_flags(a: u32, b: u32) -> u64 {
    let r = a.wrapping_add(b);
    let mut f = 0u64;
    if (a as u64) + (b as u64) > 0xFFFF_FFFF {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ r) & (b ^ r) & 0x8000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for an 8/16/32-bit ADD (r = a + b), computed at the *operand width*.
/// The native `xadd r/m8, r8` / `xadd r/m16, r16` handlers set CF/SF/OF/AF from
/// the 8/16-bit boundary (bit 7 / bit 15), not bit 31. The interpreter must
/// reproduce that so interp == native for the atomic 8/16-bit XADD path.
/// `width` is the operand width in bits (8 or 16); 32 is equivalent to
/// `add_flags`. Only the low `width` bits of `a`/`b` are considered.
pub fn add_flags_width(a: u64, b: u64, width: u32) -> u64 {
    let mask: u64 = match width {
        8 => 0xFF,
        16 => 0xFFFF,
        _ => 0xFFFF_FFFF,
    };
    let a2 = a & mask;
    let b2 = b & mask;
    let r = a2.wrapping_add(b2) & mask;
    let msb: u64 = match width {
        8 => 0x80,
        16 => 0x8000,
        _ => 0x8000_0000,
    };
    let mut f = 0u64;
    if a2 + b2 > mask {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & msb != 0 {
        f |= F_SF;
    }
    if (a2 ^ r) & (b2 ^ r) & msb != 0 {
        f |= F_OF;
    }
    if (a2 ^ b2 ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}


/// Flags for SUB / CMP at 8/16/32-bit width (like add_flags_width: the
/// carry/sign/overflow boundaries are bit 7 / bit 15 / bit 31, not bit 31).
/// `width` is the operand width in bits (8 or 16); 32 is equivalent to
/// `sub_flags`. Only the low `width` bits of `a`/`b` are considered.
pub fn sub_flags_width(a: u64, b: u64, width: u32) -> u64 {
    let mask: u64 = match width {
        8 => 0xFF,
        16 => 0xFFFF,
        _ => 0xFFFF_FFFF,
    };
    let a2 = a & mask;
    let b2 = b & mask;
    let r = a2.wrapping_sub(b2) & mask;
    let msb: u64 = match width {
        8 => 0x80,
        16 => 0x8000,
        _ => 0x8000_0000,
    };
    let mut f = 0u64;
    if a2 < b2 {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & msb != 0 {
        f |= F_SF;
    }
    if (a2 ^ b2) & (a2 ^ r) & msb != 0 {
        f |= F_OF;
    }
    if (a2 ^ b2 ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Width-generic INC/DEC flags (8/16-bit): ADD/SUB-with-1 flags but CF is
/// *preserved* (the LOCK-prefixed atomic INC/DEC paths; matches the native
/// `lock inc/dec [mem]` handlers, which capture with cap_flags_incdec).
pub fn incdec_flags_width(a: u64, width: u32, is_inc: bool, prev_flags: u64) -> u64 {
    let mut f = if is_inc {
        add_flags_width(a, 1, width)
    } else {
        sub_flags_width(a, 1, width)
    };
    f &= !F_CF;
    f |= prev_flags & F_CF;
    f
}

/// Flags for SUB / CMP (r = a - b, 32-bit).
pub fn sub_flags(a: u32, b: u32) -> u64 {
    let r = a.wrapping_sub(b);
    let mut f = 0u64;
    if (a as u64) < (b as u64) {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ b) & (a ^ r) & 0x8000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for logical ops AND/XOR/OR on a 32-bit result. CF=OF=0, AF defined 0.
pub fn logical_flags(r: u32) -> u64 {
    let mut f = 0u64;
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for INC (r = a + 1). All flags as ADD except CF is *preserved*.
pub fn inc_flags(a: u32, prev_flags: u64) -> u64 {
    let mut f = add_flags(a, 1);
    f &= !F_CF;
    f |= prev_flags & F_CF;
    f
}

/// Flags for DEC (r = a - 1). All flags as SUB except CF is *preserved*.
pub fn dec_flags(a: u32, prev_flags: u64) -> u64 {
    let mut f = sub_flags(a, 1);
    f &= !F_CF;
    f |= prev_flags & F_CF;
    f
}

/// Evaluate an OP_JCC8 condition against a flags word. Mirrors the native Jcc
/// semantics exactly (used by the interpreter and by the self-test reference).
pub fn cond_taken(cond: u8, flags: u64) -> bool {
    match cond {
        crate::vm::bytecode::COND_JE => flags & F_ZF != 0,
        crate::vm::bytecode::COND_JNE => flags & F_ZF == 0,
        crate::vm::bytecode::COND_JB => flags & F_CF != 0,
        crate::vm::bytecode::COND_JAE => flags & F_CF == 0,
        crate::vm::bytecode::COND_JG => {
            (flags & F_ZF == 0) && (((flags & F_SF) != 0) == ((flags & F_OF) != 0))
        }
        crate::vm::bytecode::COND_JGE => ((flags & F_SF) != 0) == ((flags & F_OF) != 0),
        crate::vm::bytecode::COND_JL => ((flags & F_SF) != 0) != ((flags & F_OF) != 0),
        crate::vm::bytecode::COND_JLE => {
            (flags & F_ZF != 0) || (((flags & F_SF) != 0) != ((flags & F_OF) != 0))
        }
        crate::vm::bytecode::COND_JS => flags & F_SF != 0,
        crate::vm::bytecode::COND_JNS => flags & F_SF == 0,
        crate::vm::bytecode::COND_JO => flags & F_OF != 0,
        crate::vm::bytecode::COND_JNO => flags & F_OF == 0,
        crate::vm::bytecode::COND_JP => flags & F_PF != 0,
        crate::vm::bytecode::COND_JNP => flags & F_PF == 0,
        crate::vm::bytecode::COND_JA => (flags & F_CF == 0) && (flags & F_ZF == 0),
        crate::vm::bytecode::COND_JBE => (flags & F_CF != 0) || (flags & F_ZF != 0),
        _ => false,
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// M2 — 64-bit arithmetic flags + shift flags (v22)
// ══════════════════════════════════════════════════════════════════════════════

/// Flags for 64-bit ADD (r = a + b). OF/CF on bit 63.
pub fn add_flags64(a: u64, b: u64) -> u64 {
    let r = a.wrapping_add(b);
    let mut f = 0u64;
    if a > u64::MAX - b {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ r) & (b ^ r) & 0x8000_0000_0000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Flags for 64-bit SUB / CMP (r = a - b).
pub fn sub_flags64(a: u64, b: u64) -> u64 {
    let r = a.wrapping_sub(b);
    let mut f = 0u64;
    if a < b {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ b) & (a ^ r) & 0x8000_0000_0000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Flags for 64-bit logical ops AND/XOR/OR.
pub fn logical_flags64(r: u64) -> u64 {
    let mut f = 0u64;
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// MUL/IMUL CF/OF: merge the *upper-half-overflow* condition into a previous
/// flag word, preserving every other status bit. x86 defines ONLY CF/OF for
/// MUL/IMUL (SF/ZF/AF/PF are undefined), so the other bits pass through — this
/// matches the RISC reference (`VirtualFlags::set_cf_of`) and the native
/// handler capture (`cap_flags_cf_of`), keeping interp == native == RISC.
#[inline]
pub fn muldiv_cf_of(prev: u64, ovf: bool) -> u64 {
    let mut f = prev & !(F_CF | F_OF);
    if ovf {
        f |= F_CF | F_OF;
    }
    f
}

/// 1-op MUL/IMUL upper-half overflow: CF=OF iff the upper half of the 2w-bit
/// product is non-zero (MUL) or not a sign-extension of the low half (IMUL).
#[inline]
pub fn mul_upper_ovf(low: u64, high: u64, bits: u32, signed: bool) -> bool {
    if !signed {
        return high != 0;
    }
    let mask = if bits >= 64 { u64::MAX } else { (1u64 << bits) - 1 };
    let sign_ext = if low & (1u64 << (bits - 1)) != 0 { mask } else { 0 };
    high != sign_ext
}

/// 2/3-op IMUL overflow: CF=OF iff the signed product does not fit in `bits`.
#[inline]
pub fn imul_fit_ovf(a: u64, b: u64, bits: u32) -> bool {
    if bits >= 64 {
        let p = (a as i64 as i128).wrapping_mul(b as i64 as i128);
        p != (p as i64 as i128)
    } else {
        let p = (a as i32 as i64).wrapping_mul(b as i32 as i64);
        p != (p as i32 as i64)
    }
}

/// Flags for BMI BLSR/BLSMSK/BLSI (32/64-bit). Intel SDM Vol. 2: SF, OF and
/// CF are *cleared*, ZF is set iff the result is zero. PF/AF are undefined on
/// x86 so we define them 0 (same "define undefined as 0" convention as the
/// logical ops; the native handlers mask to FLAG_MASK identically).
pub fn bls_flags(r: u64) -> u64 {
    if r == 0 {
        F_ZF
    } else {
        0
    }
}

/// Flags for BMI ANDN (32/64-bit). Intel SDM Vol. 2: SF and ZF are updated
/// from the result, CF and OF are cleared; AF/PF undefined (defined 0 here).
pub fn andn_flags(r: u64, is64: bool) -> u64 {
    let mut f = if r == 0 { F_ZF } else { 0 };
    if (is64 && (r >> 63) != 0) || (!is64 && (r & 0x8000_0000) != 0) {
        f |= F_SF;
    }
    f
}

/// Flags for 64-bit INC / DEC (CF preserved).
pub fn inc_flags64(a: u64, prev: u64) -> u64 {
    let mut f = add_flags64(a, 1);
    f &= !F_CF;
    f |= prev & F_CF;
    f
}
pub fn dec_flags64(a: u64, prev: u64) -> u64 {
    let mut f = sub_flags64(a, 1);
    f &= !F_CF;
    f |= prev & F_CF;
    f
}

/// Shift kind.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ShiftKind {
    Shl,
    Shr,
    Sar,
}

/// Flags for a 32-bit shift. CF = last bit shifted out; ZF/SF/PF from result;
/// OF is defined as 0 (x86 leaves it undefined for count != 1; we define it 0
/// and the native handler masks it out too, so both sides agree).
pub fn shift_flags(kind: ShiftKind, value: u32, count: u32, result: u32) -> u64 {
    let mut f = 0u64;
    if result == 0 {
        f |= F_ZF;
    }
    if result & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(result) {
        f |= F_PF;
    }
    if count > 0 {
        let cf = match kind {
            ShiftKind::Shl => (value >> (32 - count)) & 1,
            ShiftKind::Shr | ShiftKind::Sar => (value >> (count - 1)) & 1,
        };
        if cf != 0 {
            f |= F_CF;
        }
    }
    f
}

/// Flags for a 64-bit shift. Same convention as `shift_flags` but on 64-bit
/// operands: CF = last bit shifted out; ZF/SF/PF from the result; OF and AF
/// defined as 0 (native handler masks them out too).
pub fn shift_flags64(kind: ShiftKind, value: u64, count: u32, result: u64) -> u64 {
    let mut f = 0u64;
    if result == 0 {
        f |= F_ZF;
    }
    if result & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(result as u32) {
        f |= F_PF;
    }
    if count > 0 {
        let cf = match kind {
            ShiftKind::Shl => (value >> (64 - count)) & 1,
            ShiftKind::Shr | ShiftKind::Sar => (value >> (count - 1)) & 1,
        };
        if cf != 0 {
            f |= F_CF;
        }
    }
    f
}
