// ==============================================================================
// BTG v21 - VM Flag Model (x86 status-flag semantics, pure Rust)
// ==============================================================================
//
// M1 of the code-virtualization roadmap. The VM now models the x86 status
// flags (CF/PF/AF/ZF/SF/OF) in a single 64-bit STATE_FLAGS slot using the same
// bit positions as the real RFLAGS register (see bytecode.rs). These helpers
// compute the flag word that x86 would set for each operation, exactly matching
// the semantics of the native handlers (which use pushfq to capture real flags).
//
// This module is the *single source of truth* for the flag math. The reference
// interpreter (interp.rs) uses it, and the self-test cross-checks it against
// the native x86-64 handlers generated by handlers.rs.
//
// Semantics follow Intel SDM for the 32-bit forms we virtualize:
//   * ADD/SUB/CMP/INC/DEC : all six flags defined (INC/DEC preserve CF).
//   * AND/XOR/OR          : ZF/SF/PF defined; CF=OF=0; AF is undefined on x86,
//                           so we *define* it as 0 (the native handler masks it
//                           out too, keeping the two sides identical).
//   * IMUL/MUL/DIV        : flags left untouched in M1 (not consumed by any
//                           virtualized target; documented limitation).
// ==============================================================================


use crate::vm::bytecode::{F_AF, F_CF, F_OF, F_PF, F_SF, F_ZF};

/// x86 PF: set iff the low byte has an even number of set bits.
#[inline]
fn parity8(r: u32) -> bool {
    (r as u8).count_ones() % 2 == 0
}

/// Flags for ADD (r = a + b, 32-bit).
pub fn add_flags(a: u32, b: u32) -> u64 {
    let r = a.wrapping_add(b);
    let mut f = 0u64;
    if (a as u64) + (b as u64) > 0xFFFF_FFFF {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ r) & (b ^ r) & 0x8000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for SUB / CMP (r = a - b, 32-bit).
pub fn sub_flags(a: u32, b: u32) -> u64 {
    let r = a.wrapping_sub(b);
    let mut f = 0u64;
    if (a as u64) < (b as u64) {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ b) & (a ^ r) & 0x8000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for logical ops AND/XOR/OR on a 32-bit result. CF=OF=0, AF defined 0.
pub fn logical_flags(r: u32) -> u64 {
    let mut f = 0u64;
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(r) {
        f |= F_PF;
    }
    f
}

/// Flags for INC (r = a + 1). All flags as ADD except CF is *preserved*.
pub fn inc_flags(a: u32, prev_flags: u64) -> u64 {
    let mut f = add_flags(a, 1);
    f &= !F_CF;
    f |= prev_flags & F_CF;
    f
}

/// Flags for DEC (r = a - 1). All flags as SUB except CF is *preserved*.
pub fn dec_flags(a: u32, prev_flags: u64) -> u64 {
    let mut f = sub_flags(a, 1);
    f &= !F_CF;
    f |= prev_flags & F_CF;
    f
}

/// Evaluate an OP_JCC8 condition against a flags word. Mirrors the native Jcc
/// semantics exactly (used by the interpreter and by the self-test reference).
pub fn cond_taken(cond: u8, flags: u64) -> bool {
    match cond {
        crate::vm::bytecode::COND_JE => flags & F_ZF != 0,
        crate::vm::bytecode::COND_JNE => flags & F_ZF == 0,
        crate::vm::bytecode::COND_JB => flags & F_CF != 0,
        crate::vm::bytecode::COND_JAE => flags & F_CF == 0,
        crate::vm::bytecode::COND_JG => {
            (flags & F_ZF == 0) && (((flags & F_SF) != 0) == ((flags & F_OF) != 0))
        }
        crate::vm::bytecode::COND_JGE => ((flags & F_SF) != 0) == ((flags & F_OF) != 0),
        crate::vm::bytecode::COND_JL => ((flags & F_SF) != 0) != ((flags & F_OF) != 0),
        crate::vm::bytecode::COND_JLE => {
            (flags & F_ZF != 0) || (((flags & F_SF) != 0) != ((flags & F_OF) != 0))
        }
        crate::vm::bytecode::COND_JS => flags & F_SF != 0,
        crate::vm::bytecode::COND_JNS => flags & F_SF == 0,
        crate::vm::bytecode::COND_JO => flags & F_OF != 0,
        crate::vm::bytecode::COND_JNO => flags & F_OF == 0,
        crate::vm::bytecode::COND_JP => flags & F_PF != 0,
        crate::vm::bytecode::COND_JNP => flags & F_PF == 0,
        crate::vm::bytecode::COND_JA => (flags & F_CF == 0) && (flags & F_ZF == 0),
        crate::vm::bytecode::COND_JBE => (flags & F_CF != 0) || (flags & F_ZF != 0),
        _ => false,
    }
}

// ══════════════════════════════════════════════════════════════════════════════
// M2 — 64-bit arithmetic flags + shift flags (v22)
// ══════════════════════════════════════════════════════════════════════════════

/// Flags for 64-bit ADD (r = a + b). OF/CF on bit 63.
pub fn add_flags64(a: u64, b: u64) -> u64 {
    let r = a.wrapping_add(b);
    let mut f = 0u64;
    if a > u64::MAX - b {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ r) & (b ^ r) & 0x8000_0000_0000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Flags for 64-bit SUB / CMP (r = a - b).
pub fn sub_flags64(a: u64, b: u64) -> u64 {
    let r = a.wrapping_sub(b);
    let mut f = 0u64;
    if a < b {
        f |= F_CF;
    }
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if (a ^ b) & (a ^ r) & 0x8000_0000_0000_0000 != 0 {
        f |= F_OF;
    }
    if (a ^ b ^ r) & 0x10 != 0 {
        f |= F_AF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Flags for 64-bit logical ops AND/XOR/OR.
pub fn logical_flags64(r: u64) -> u64 {
    let mut f = 0u64;
    if r == 0 {
        f |= F_ZF;
    }
    if r & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(r as u32) {
        f |= F_PF;
    }
    f
}

/// Flags for 64-bit INC / DEC (CF preserved).
pub fn inc_flags64(a: u64, prev: u64) -> u64 {
    let mut f = add_flags64(a, 1);
    f &= !F_CF;
    f |= prev & F_CF;
    f
}
pub fn dec_flags64(a: u64, prev: u64) -> u64 {
    let mut f = sub_flags64(a, 1);
    f &= !F_CF;
    f |= prev & F_CF;
    f
}

/// Shift kind.
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum ShiftKind {
    Shl,
    Shr,
    Sar,
}

/// Flags for a 32-bit shift. CF = last bit shifted out; ZF/SF/PF from result;
/// OF is defined as 0 (x86 leaves it undefined for count != 1; we define it 0
/// and the native handler masks it out too, so both sides agree).
pub fn shift_flags(kind: ShiftKind, value: u32, count: u32, result: u32) -> u64 {
    let mut f = 0u64;
    if result == 0 {
        f |= F_ZF;
    }
    if result & 0x8000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(result) {
        f |= F_PF;
    }
    if count > 0 {
        let cf = match kind {
            ShiftKind::Shl => (value >> (32 - count)) & 1,
            ShiftKind::Shr | ShiftKind::Sar => (value >> (count - 1)) & 1,
        };
        if cf != 0 {
            f |= F_CF;
        }
    }
    f
}

/// Flags for a 64-bit shift. Same convention as `shift_flags` but on 64-bit
/// operands: CF = last bit shifted out; ZF/SF/PF from the result; OF and AF
/// defined as 0 (native handler masks them out too).
pub fn shift_flags64(kind: ShiftKind, value: u64, count: u32, result: u64) -> u64 {
    let mut f = 0u64;
    if result == 0 {
        f |= F_ZF;
    }
    if result & 0x8000_0000_0000_0000 != 0 {
        f |= F_SF;
    }
    if parity8(result as u32) {
        f |= F_PF;
    }
    if count > 0 {
        let cf = match kind {
            ShiftKind::Shl => (value >> (64 - count)) & 1,
            ShiftKind::Shr | ShiftKind::Sar => (value >> (count - 1)) & 1,
        };
        if cf != 0 {
            f |= F_CF;
        }
    }
    f
}
