// @generated by tools/btg_codegen --emit-fallback  (seed; safe to regenerate)
// =============================================================================
// Reviewed lowering fallback for instructions that otherwise hit the RISC
// lifter's `_ => unsupported` arm. Compiled ONLY under the `codegen_fallback`
// feature; the default production lifter never sees it.
//
// Matching is by the instruction's mnemonic DEBUG STRING — exactly the form the
// coverage auditor (`vm-coverage`) records. Consequences by design:
//   * An entry that does not correspond to a real iced-x86 mnemonic simply
//     never fires. It can never be a compile error and never a mis-lowering.
//   * The generator emits these strings straight from the coverage DB, so every
//     emitted entry is guaranteed to match at runtime.
//
// Every mnemonic in this seed is architecturally effect-free in the
// single-threaded reference semantics (cache/prefetch hints, memory-ordering
// fences, CET landing pads). Lowering them to NO micro-op is exact — the same
// treatment the hand-written lifter already gives NOP/PAUSE.
// =============================================================================

use super::RiscLifter;
use anyhow::Result;
use iced_x86::Instruction;

impl RiscLifter {
    /// Try to lower an otherwise-unsupported instruction with a generated rule.
    /// Returns `Ok(true)` when handled (any micro-ops have been pushed).
    ///
    /// Takes `&mut self` because future, non-no-op generated arms will push
    /// onto `self.desynth`; the current effect-free class pushes nothing.
    pub(crate) fn try_generated_fallback(&mut self, inst: &Instruction) -> Result<bool> {
        let mnemonic = format!("{:?}", inst.mnemonic());

        if is_effect_free_hint(&mnemonic) {
            // Architectural no-op: emit no micro-op (cf. the NOP/PAUSE arm).
            return Ok(true);
        }

        Ok(false)
    }
}

/// Effect-free hint / fence / CET instructions: no register, memory, or flag
/// effect in the single-threaded reference model.
fn is_effect_free_hint(mnemonic: &str) -> bool {
    matches!(
        mnemonic,
        "Prefetcht0"
            | "Prefetcht1"
            | "Prefetcht2"
            | "Prefetchnta"
            | "Prefetchw"
            | "Prefetchwt1"
            | "Sfence"
            | "Lfence"
            | "Mfence"
            | "Clflush"
            | "Clflushopt"
            | "Clwb"
            | "Cldemote"
            | "Endbr32"
            | "Endbr64"
    )
}
