// ==============================================================================
// BTG - Pipeline Artifact Structures (Domit §46, §76)
// ==============================================================================
// Strongly-typed output structures produced across compilation passes.
// ==============================================================================

use crate::pe::builder::SectionData;
use crate::pipeline::selective_vm::PolyVmRegion;
use crate::pipeline::PipelineContext;
use anyhow::Result;
use std::marker::PhantomData;
use std::path::Path;

/// Typestate wrapper used by programmatic pipelines. A pass can only be called
/// when its predecessor artifact exists, so library users cannot accidentally
/// build or emit a half-populated mutable `PipelineContext`.
pub struct StagedPipeline<S> {
    ctx: PipelineContext,
    output: Option<Vec<u8>>,
    _stage: PhantomData<S>,
}

pub struct InputStage;
pub struct AnalyzedStage;
pub struct LaidOutStage;
pub struct ProtectedStage;
pub struct ValidatedStage;

impl StagedPipeline<InputStage> {
    pub fn new(ctx: PipelineContext) -> Self {
        Self {
            ctx,
            output: None,
            _stage: PhantomData,
        }
    }

    pub fn analyze(mut self) -> Result<StagedPipeline<AnalyzedStage>> {
        crate::pipeline::pass1_slice::run(&mut self.ctx)?;
        Ok(self.advance())
    }
}

impl StagedPipeline<AnalyzedStage> {
    pub fn layout(mut self) -> Result<StagedPipeline<LaidOutStage>> {
        crate::pipeline::pass2_shuffle::run(&mut self.ctx)?;
        crate::pipeline::pass3_encode::run(&mut self.ctx)?;
        crate::pipeline::pass4_section::run(
            &mut self.ctx,
            false,
            crate::dispatcher::antidebug::AntiDebugPolicy::Trap,
            true,
            false,
        )?;
        Ok(self.advance())
    }
}

impl StagedPipeline<LaidOutStage> {
    pub fn protect(mut self, crypto_coverage: u32) -> Result<StagedPipeline<ProtectedStage>> {
        let relayed = self.ctx.target_info.relayed_sections.clone();
        crate::pipeline::patch_data::run(&mut self.ctx, relayed)?;
        crate::pipeline::crypto::run(
            &mut self.ctx,
            true,
            false,
            crate::dispatcher::antidebug::AntiDebugPolicy::Trap,
            false,
            crypto_coverage,
            true,
            false,
            false,
            false,
        )?;
        Ok(self.advance())
    }
}

impl StagedPipeline<ProtectedStage> {
    pub fn validate(
        self,
        effective: &crate::protection_profile::ResolvedConfig,
    ) -> Result<StagedPipeline<ValidatedStage>> {
        let bytes = crate::pipeline::build::run(&self.ctx, None)?;
        crate::pipeline::validate::run(&self.ctx, &bytes)?;
        crate::pipeline::validate::validate_effective_profile(&self.ctx, effective, &bytes)?
            .ensure_strict()?;
        Ok(StagedPipeline {
            ctx: self.ctx,
            output: Some(bytes),
            _stage: PhantomData,
        })
    }
}

impl StagedPipeline<ValidatedStage> {
    pub fn emit(mut self, output: Option<&Path>) -> Result<Vec<u8>> {
        let bytes = self
            .output
            .take()
            .ok_or_else(|| anyhow::anyhow!("validated pipeline lost its output artifact"))?;
        if let Some(path) = output {
            std::fs::write(path, &bytes)?;
        }
        Ok(bytes)
    }
}

impl<S> StagedPipeline<S> {
    fn advance<T>(self) -> StagedPipeline<T> {
        StagedPipeline {
            ctx: self.ctx,
            output: self.output,
            _stage: PhantomData,
        }
    }
}

/// VM compilation outputs generated by SelectiveVmPass / PolyVmEmbed.
#[derive(Debug, Clone, Default)]
pub struct VmArtifact {
    pub section: Option<SectionData>,
    pub entry_va: u64,
    pub regions: Vec<PolyVmRegion>,
    pub rejected_regions: usize,
}

/// Cryptographic outputs generated by bootstub placement and stream cipher.
#[derive(Debug, Clone, Default)]
pub struct CryptoArtifact {
    pub boot_entry_offset: u32,
    pub payload_section: Option<SectionData>,
    pub payload_rva: u32,
    pub payload_len: u32,
    pub entry_block_id: usize,
    pub entry_seed: u32,
    pub mba_constant: u32,
}

/// Final PE image artifact produced after section patching and relocations.
#[derive(Debug, Clone, Default)]
pub struct PeArtifact {
    pub patched_sections: Vec<SectionData>,
    pub btg_section: Option<SectionData>,
    pub new_entry_rva: u32,
}
