// ==============================================================================
// BTG - Pipeline Artifact Structures (Domit §46, §76)
// ==============================================================================
// Strongly-typed output structures produced across compilation passes.
// ==============================================================================

use crate::pe::builder::SectionData;
use crate::pipeline::selective_vm::PolyVmRegion;

/// VM compilation outputs generated by SelectiveVmPass / PolyVmEmbed.
#[derive(Debug, Clone, Default)]
pub struct VmArtifact {
    pub section: Option<SectionData>,
    pub entry_va: u64,
    pub regions: Vec<PolyVmRegion>,
    pub rejected_regions: usize,
}

/// Cryptographic outputs generated by bootstub placement and stream cipher.
#[derive(Debug, Clone, Default)]
pub struct CryptoArtifact {
    pub boot_entry_offset: u32,
    pub payload_section: Option<SectionData>,
    pub payload_rva: u32,
    pub payload_len: u32,
    pub entry_block_id: usize,
    pub entry_seed: u32,
    pub mba_constant: u32,
}

/// Final PE image artifact produced after section patching and relocations.
#[derive(Debug, Clone, Default)]
pub struct PeArtifact {
    pub patched_sections: Vec<SectionData>,
    pub btg_section: Option<SectionData>,
    pub new_entry_rva: u32,
}
