// ==============================================================================
// BTG PE - Base Relocation (.reloc) Directory Builder
// ==============================================================================
//
// P0-⑦: relocation-aware output so the packed binary keeps ASLR (DYNAMIC_BASE /
// HIGH_ENTROPY_VA). The injected `.textb`/`.btgvm`/boot-stub code embeds absolute
// image-base-relative VAs at 8-byte-aligned slots. A correct PE `.reloc` data
// directory lets the OS loader rebase the whole image at load time (before the
// boot stub runs), so a non-preferred base no longer crashes the packer's own
// machine code.
//
// The directory is generated by scanning the final sections for 8-byte-aligned
// values that fall inside [image_base, image_base + size_of_image): each such
// slot is a pointer into the image and gets an IMAGE_REL_BASED_DIR64 entry.
// This reproduces the original .reloc slots (relayed sections' pointers) and
// the injected ones (VM entry stubs, handler tables, dispatcher, boot stub
// imm64s) in one pass.
//
// At-rest-encrypted regions are EXCLUDED: the loader runs BEFORE the boot stub
// decrypts, so a relocation applied to ciphertext would corrupt the decryption.
// The caller supplies the encrypted-at-rest RVA ranges (code blocks, string
// runs, IAT resolve table, vm-oep preserved-.text runs) and those slots are
// skipped.
// ==============================================================================

use crate::pe::builder::{DataDirectory, SectionData};

/// IMAGE_REL_BASED_DIR64 — 64-bit absolute-address fixup (PE32+).
pub const IMAGE_REL_BASED_DIR64: u16 = 10;

/// x86-64 `mov r64, imm64` = REX.W(0x48-0x4F, W bit set) + opcode 0xB8-0xBF +
/// 8-byte little-endian immediate. The immediate starts at **offset+2** (not
/// 8-byte aligned), so the 8-aligned slot scan in `build_reloc_directory` misses
/// it. Scan a code blob for this exact instruction pattern and return the byte
/// offset of each immediate whose value falls inside `[va_lo, va_hi)`.
///
/// This is provenance-by-pattern: unlike the 8-aligned value scan (which can
/// false-positive on a random constant that happens to land in the image range),
/// here the slot is provably the operand of a `mov r64, imm64` instruction —
/// exactly the encoding the packer's own generators (`movi`) use to embed module
/// entry / table / state / stack-base VAs into the dispatcher and boot stub.
/// Derived keys (init_key / mba_a / mba_b) are naturally excluded because they
/// are not inside the image range.
pub(crate) fn scan_mov_imm64_slots(code: &[u8], va_lo: u64, va_hi: u64) -> Vec<u32> {
    let mut out = Vec::new();
    let mut i = 0usize;
    while i + 10 <= code.len() {
        // REX.W (W bit 0x08 set) + 0xB8..=0xBF (mov r64, imm64).
        if (code[i] & 0x08) != 0 && (0xB8..=0xBF).contains(&code[i + 1]) {
            let imm = u64::from_le_bytes(code[i + 2..i + 10].try_into().unwrap());
            if imm >= va_lo && imm < va_hi {
                out.push((i + 2) as u32);
            }
            i += 10;
            continue;
        }
        i += 1;
    }
    out
}

/// Result of building the relocation directory.
pub struct RelocOutput {
    /// The `.reloc` section to append to the image (VA must be set by the caller).
    pub section: SectionData,
    /// The Base Relocation DataDirectory entry (VA is a placeholder until placed).
    pub directory: DataDirectory,
}

/// Build the `.reloc` directory bytes from the final image sections.
///
/// `sections` are the relayed + injected sections with FINAL `virtual_address`
/// and `bytes` (raw). `image_base` and `size_of_image` bound the pointer range.
/// `encrypted_rva_ranges` is a list of `(rva, len)` of at-rest-ciphertext ranges
/// to skip (loader relocation there would corrupt the ciphertext).
///
/// Returns `None` if there are no relocatable slots (no ASLR needed).
pub fn build_reloc_directory(
    sections: &[SectionData],
    image_base: u64,
    size_of_image: u32,
    encrypted_rva_ranges: &[(u32, u32)],
) -> Option<RelocOutput> {
    let va_lo = image_base;
    let va_hi = image_base.wrapping_add(size_of_image as u64);

    // Per-4KB-page: list of (page_rva, offset_within_page).
    let mut pages: std::collections::BTreeMap<u32, Vec<u16>> = std::collections::BTreeMap::new();

    let in_encrypted = |slot_rva: u32| -> bool {
        encrypted_rva_ranges
            .iter()
            .any(|&(r, l)| l > 0 && slot_rva >= r && slot_rva < r.wrapping_add(l))
    };

    for sec in sections {
        let sec_rva = sec.virtual_address;
        let limit = (sec.bytes.len() as u32).min(sec.virtual_size.max(sec.bytes.len() as u32));
        let n_slots = (limit / 8) as usize;
        for i in 0..n_slots {
            let slot_rva = sec_rva.wrapping_add((i * 8) as u32);
            if in_encrypted(slot_rva) {
                continue;
            }
            let v = u64::from_le_bytes([sec.bytes[i * 8], sec.bytes[i * 8 + 1], sec.bytes[i * 8 + 2], sec.bytes[i * 8 + 3], sec.bytes[i * 8 + 4], sec.bytes[i * 8 + 5], sec.bytes[i * 8 + 6], sec.bytes[i * 8 + 7]]);
            if v < va_lo || v >= va_hi {
                continue;
            }
            let page = slot_rva & !0xFFF;
            let off_in_page = (slot_rva & 0xFFF) as u16;
            pages.entry(page).or_default().push(off_in_page);
        }
        // P0-5: 8-정렬 슬롯 스캔만으로는 injected 코드의 `mov r64, imm64` 즉시값
        // (명령어 offset+2, 비정렬) 절대 VA 를 놓친다 — 보호기/부트 스텁/디스패처가
        // R8/R13/R14/R15/RDX/모듈 엔트리 VA 를 imm64 로 박는데, ASLR 재배치가 빠지면
        // preferred base != actual base 에서 잘못된 주소로 점프해 크래시한다.
        // `mov r64, imm64` = REX.W(0x48-0x4F) + 0xB8-0xBF + 8B immediate (LE) 패턴으로
        // 이미지 범위 내 값만 정확히 추적한다 (임의 데이터가 8-정렬 우연 일치로
        // 오탐되는 8-정렬 스캔보다 정밀 — 값이 실제 명령어 피연산자임이 보장된다).
        for off in scan_mov_imm64_slots(&sec.bytes, va_lo, va_hi) {
            let slot_rva = sec_rva.wrapping_add(off);
            if in_encrypted(slot_rva) {
                continue;
            }
            let page = slot_rva & !0xFFF;
            let off_in_page = (slot_rva & 0xFFF) as u16;
            pages.entry(page).or_default().push(off_in_page);
        }
    }

    if pages.is_empty() {
        return None;
    }

    // Serialize: per page a block of {PageRVA u32, BlockSize u32, entries u16[]}.
    // BlockSize must be DWORD-aligned (multiple of 4): an odd entry count is
    // padded with one IMAGE_REL_BASED_ABSOLUTE (type 0) dummy entry.
    let mut bytes = Vec::with_capacity(pages.len() * 12);
    for (page_rva, mut offs) in pages {
        offs.sort_unstable();
        offs.dedup();
        let mut n = offs.len();
        if n % 2 == 1 {
            n += 1; // pad to DWORD alignment with an ABSOLUTE entry
        }
        let block_size = 8 + n * 2;
        bytes.extend_from_slice(&page_rva.to_le_bytes());
        bytes.extend_from_slice(&(block_size as u32).to_le_bytes());
        for &off in &offs {
            bytes.extend_from_slice(&((off as u16) | (IMAGE_REL_BASED_DIR64 << 12)).to_le_bytes());
        }
        if n > offs.len() {
            bytes.extend_from_slice(&0u16.to_le_bytes()); // ABSOLUTE pad
        }
    }

    let size = bytes.len() as u32;
    let section = SectionData {
        name: ".reloc".to_string(),
        virtual_address: 0, // caller assigns (after last section)
        virtual_size: size,
        characteristics: 0x4200_0040, // CNT_INITIALIZED_DATA | MEM_READ
        bytes,
    };
    Some(RelocOutput {
        section,
        directory: DataDirectory { virtual_address: 0, size },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sec(name: &str, rva: u32, bytes: Vec<u8>) -> SectionData {
        SectionData {
            name: name.to_string(),
            virtual_address: rva,
            virtual_size: bytes.len() as u32,
            characteristics: 0,
            bytes,
        }
    }

    #[test]
    fn dir64_entries_emitted_for_image_pointers() {
        let ib: u64 = 0x14000_0000;
        let mut b = vec![0u8; 0x30];
        // slot @ +0x10 = pointer into image (VA ib + 0x1000)
        b[0x10..0x18].copy_from_slice(&(ib + 0x1000).to_le_bytes());
        // slot @ +0x18 = pointer into image (VA ib + 0x9000)
        b[0x18..0x20].copy_from_slice(&(ib + 0x9000).to_le_bytes());
        // slot @ +0x20 = non-pointer constant (not relocated)
        b[0x20..0x28].copy_from_slice(&0x1122_3344_5566_7788u64.to_le_bytes());
        let sections = vec![sec(".textb", 0x1000, b)];
        let out = build_reloc_directory(&sections, ib, 0x200000, &[]).expect("relocs");
        // Both pointers fall in the same 4KB page (0x1000), so one block: 8 + 2*2.
        assert_eq!(out.directory.size, 12);
        let block = &out.section.bytes;
        assert_eq!(u32::from_le_bytes(block[0..4].try_into().unwrap()), 0x1000); // page
        assert_eq!(u32::from_le_bytes(block[4..8].try_into().unwrap()), 12); // block size
        // entry0: offset 0x10, DIR64
        let e0 = u16::from_le_bytes(block[8..10].try_into().unwrap());
        assert_eq!(e0 >> 12, IMAGE_REL_BASED_DIR64);
        assert_eq!(e0 & 0xFFF, 0x10);
        // entry1: offset 0x18
        let e1 = u16::from_le_bytes(block[10..12].try_into().unwrap());
        assert_eq!(e1 >> 12, IMAGE_REL_BASED_DIR64);
        assert_eq!(e1 & 0xFFF, 0x18);
    }

    #[test]
    fn encrypted_range_slots_are_skipped() {
        let ib: u64 = 0x14000_0000;
        let mut b = vec![0u8; 0x40];
        b[0x10..0x18].copy_from_slice(&(ib + 0x1000).to_le_bytes()); // plaintext slot
        b[0x20..0x28].copy_from_slice(&(ib + 0x2000).to_le_bytes()); // inside encrypted range
        let sections = vec![sec(".textb", 0x1000, b)];
        let enc = vec![(0x1020u32, 0x10u32)];
        let out = build_reloc_directory(&sections, ib, 0x200000, &enc).expect("relocs");
        // only the 0x10 slot survives -> block 8 + 2 (entry) + 2 (DWORD pad) = 12 bytes
        assert_eq!(out.directory.size, 12);
        let e0 = u16::from_le_bytes(out.section.bytes[8..10].try_into().unwrap());
        assert_eq!(e0 & 0xFFF, 0x10);
        // the pad entry must be ABSOLUTE (type 0)
        let pad = u16::from_le_bytes(out.section.bytes[10..12].try_into().unwrap());
        assert_eq!(pad >> 12, 0);
    }

    #[test]
    fn no_relocs_when_no_image_pointers() {
        let ib: u64 = 0x14000_0000;
        let mut b = vec![0u8; 0x20];
        b[0x10..0x18].copy_from_slice(&0x1122_3344_5566_7788u64.to_le_bytes());
        let sections = vec![sec(".data", 0x3000, b)];
        assert!(build_reloc_directory(&sections, ib, 0x200000, &[]).is_none());
    }

    #[test]
    fn multi_page_blocks() {
        let ib: u64 = 0x14000_0000;
        let mut b = vec![0u8; 0x3000];
        b[0x1000..0x1008].copy_from_slice(&(ib + 0x1000).to_le_bytes()); // slot RVA 0x2000
        b[0x2008..0x2010].copy_from_slice(&(ib + 0x9000).to_le_bytes()); // slot RVA 0x3008
        let sections = vec![sec(".textb", 0x1000, b)];
        let out = build_reloc_directory(&sections, ib, 0x200000, &[]).expect("relocs");
        // two pages (0x2000, 0x3000), 1 entry each + DWORD pad -> 12 bytes per block
        assert_eq!(out.directory.size, 24);
        let p0 = u32::from_le_bytes(out.section.bytes[0..4].try_into().unwrap());
        let p1 = u32::from_le_bytes(out.section.bytes[12..16].try_into().unwrap());
        assert_eq!(p0, 0x2000);
        assert_eq!(p1, 0x3000);
    }

    /// P0-5: injected `mov r64, imm64` 절대 VA (명령어 offset+2, 비정렬) 슬롯이
    /// .reloc 에 잡혀야 한다 — 8-정렬 스캔만으로는 놓치는 보호기/디스패처/부트 스텁
    /// imm64 이며, 이미지 범위 밖 값(파생 키 등)은 제외된다.
    #[test]
    fn mov_imm64_slots_get_reloc_entries() {
        let ib: u64 = 0x14000_0000;
        // 코드 블록: 3바이트 서브루틴 시작 + `mov r8, imm64` (49 B8 + imm64) + 계속.
        // imm64 는 bytecode_va (이미지 내부, 8-정렬 아님) → reloc 되어야 한다.
        let mut b = vec![0u8; 0x40];
        b[0x00] = 0x90; // nop
        b[0x01] = 0x90; // nop
        b[0x02] = 0x49; // REX.W+R.B (mov r8, imm64)
        b[0x03] = 0xB8;
        b[0x04..0x0C].copy_from_slice(&(ib + 0x4000).to_le_bytes()); // 이미지 내부 VA
        // 별도 mov r10, imm64 (4D B8) — 파생 키 (이미지 밖) → 제외.
        b[0x0C] = 0x4D;
        b[0x0D] = 0xB8;
        b[0x0E..0x16].copy_from_slice(&0xDEAD_BEEF_CAFE_F000u64.to_le_bytes());
        let sections = vec![sec(".btgvm", 0x1000, b)];
        let out = build_reloc_directory(&sections, ib, 0x200000, &[]).expect("relocs");
        // 유일한 reloc 슬롯: imm64 at offset 0x04 → RVA 0x1004.
        let block = &out.section.bytes;
        assert_eq!(out.directory.size, 12); // 1 entry + DWORD pad
        let e0 = u16::from_le_bytes(block[8..10].try_into().unwrap());
        assert_eq!(e0 >> 12, IMAGE_REL_BASED_DIR64);
        assert_eq!(e0 & 0xFFF, 0x04, "imm64 slot at instruction offset+2 (not 8-aligned)");
        let pad = u16::from_le_bytes(block[10..12].try_into().unwrap());
        assert_eq!(pad >> 12, 0, "pad entry is ABSOLUTE");
    }

    /// P0-5: scan_mov_imm64_slots 는 실제 `mov r64, imm64` 명령만 잡고, 8-정렬
    /// 임의 데이터(우연 일치)는 잡지 않는다 — 오탐 방지.
    #[test]
    fn scan_mov_imm64_rejects_plain_data() {
        let ib: u64 = 0x14000_0000;
        // 8-정렬된 평문 데이터가 이미지 범위 값을 갖더라도 8-정렬 스캔은 잡지만,
        // mov-imm64 패턴 스캔은 실제 명령어 인코딩이 아니면 잡지 않는다.
        let mut b = vec![0u8; 0x20];
        b[0x00..0x08].copy_from_slice(&(ib + 0x1000).to_le_bytes()); // plain data (8-aligned)
        let slots = scan_mov_imm64_slots(&b, ib, ib + 0x200000);
        assert!(slots.is_empty(), "plain data must not be caught as mov-imm64");
        // 반대로 실제 명령어 패턴(REX.W + 0xB8 + imm64 in range)은 정확히 offset+2.
        let mut c = vec![0x48, 0xB8, 0, 0, 0, 0, 0, 0, 0, 0]; // mov rax, imm64
        c[2..10].copy_from_slice(&(ib + 0x2000).to_le_bytes());
        let slots = scan_mov_imm64_slots(&c, ib, ib + 0x200000);
        assert_eq!(slots, vec![2], "mov-imm64 immediate slot at offset+2");
        // 이미지 범위 밖 값은 제외.
        c[2..10].copy_from_slice(&0x7000_0000_0000_0000u64.to_le_bytes());
        let slots = scan_mov_imm64_slots(&c, ib, ib + 0x200000);
        assert!(slots.is_empty(), "out-of-range imm64 must be excluded");
    }
}